### PR TITLE
Nerfed notification settings from #6

### PR DESCRIPTION
**Pull request by Dancanplay**

### CODE REVIEW

**Comment by Dancanplay** [comment]
I also themed the search box dark

**Comment by ItsiAdam** [comment]
It'll be fixed in Full Dark 2.0 as far as I am aware.

**Comment by Dancanplay** [comment]
Okay, let's rather wait days... weeks... months.. years...

**Comment by fluffingtons** [comment]
If you'd like, you could test 2.0. It was remade from scratch so I need someone other than myself to test it.

**Comment by Dancanplay** [comment]
@fluffingtons No problem, hit me up on Discord: deancan#4961

**Pull request closed without merging**
